name: Terraform Github Runners

on:
  workflow_dispatch:
    inputs:
      tfaction:
        type: choice
        description: Terraform Action
        options: 
        - apply
        - destroy

env:
  terraform_directory: "${{github.workspace}}"
  ARM_CLIENT_ID: ${{secrets.AZ_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZ_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZ_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZ_TENANT_ID}}
  ARM_ACCESS_KEY: ${{secrets.AZ_ARM_ACCESS_KEY}}
  TF_VAR_az_into365exch_infra_github_runner_token: ${{secrets.AZ_INTO365EXCH_INFRA_GITHUB_RUNNER_TOKEN}}
  TF_VAR_az_into365exch_cust_github_runner: ${{secrets.AZ_INTO365EXCH_CUST_GITHUB_RUNNER}}

jobs:
  build:
    name: "Terraform Apply"
    if: "${{github.event.inputs.tfaction == 'apply'}}"
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      repository-projects: read

    defaults:
      run:
        working-directory: ${{env.terraform_directory}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Setup `terraform`
        uses: hashicorp/setup-terraform@v2
    
      - name: Terraform Init
        id: init
        run: "terraform init -input=false"
    
      - name: Terraform Validate
        id: validate
        run: "terraform validate -no-color"
    
      - name: Terraform Apply
        id: apply
        run: "terraform apply -auto-approve"
  
  teardown:
    name: "Terraform Destroy"
    if: "${{github.event.inputs.tfaction == 'destroy'}}"
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      repository-projects: read
    
    defaults:
      run:
        working-directory: ${{env.terraform_directory}}
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Setup `terraform`
        uses: hashicorp/setup-terraform@v2
    
      - name: Terraform Init
        id: init
        run: "terraform init -input=false -backend-config=key=ucgithubrunners.terraform.tfstate"
      
      - name: Terraform Destroy
        id: destroy
        run: "terraform destroy -auto-approve"
